name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
          echo "VITE_BASE_URL_HARVARD=${{ secrets.VITE_BASE_URL_HARVARD }}" >> .env
          echo "VITE_BASE_URL_CMA=${{ secrets.VITE_BASE_URL_CMA }}" >> .env

      - run: npm run build

      - run: ls -la dist

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
